version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    environment:
      - ENABLE_IPV6: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    environment:
      - DEFAULT_EMAIL: contact@nekomimi.pet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
    network_mode: bridge

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
